### ISSUE TITLE
how to get out all dot from the address?

### ISSUE THREAD

**Issue by lijianl** [polkadot-js/docs#116]
Failed at this way: 
```
// totalAmount
let info = await api.tx.balances.transferKeepAlive(toAddr, amount).paymentInfo(pair);
// fee
let fee = info.partialFee.toNumber();
// sendAmount - totalAmount - fee
let transfer = api.tx.balances.transferKeepAlive(toAddr, amount-fee);
let txhash = await transfer.signAndSend(pair);
```
sendAmount  = totalAmount - fee.
why tx on-chain is always failed...

**Comment by jacogr** [comment]
Substrate has 2 transfer methods -

- balances.transfer
- balances.transferKeepAlive

the difference is the following: the keep alive version will fail when the remaining balance falls below the existential deposit. The transfer will allow the chain to reap the account if the balance falls below existential. 

So in the example above, since you are using keep alive, the account will never be reaped and will always be kept to at least existential.

**Comment by lijianl** [comment]
> transfer will allow the chain to reap t

tks, I tried to reap the account with transfer and succeed, 
could you give me some API-docs or link about the difference above so that I can learn more

**Comment by jacogr** [comment]
In Substrate, all the available calls are as configured on the runtime. (Some chains don't have the balances module for instance). So the API received the metadata from the chain and decorates based on that.

The metadata has some documentation attached, see for transfer here - https://polkadot.js.org/docs/substrate/extrinsics#transferdest-lookupsource-value-compactbalance

(The above is just the documentation supplied by the runtime, with the actual source being https://github.com/paritytech/substrate/blob/master/frame/balances/src/lib.rs#L437)
