### ISSUE TITLE
Which queries support the use of `.multi`?

### ISSUE THREAD

**Issue by alfarok** [polkadot-js/docs#359]
After reading through [docs/api/start/api.query.multi](https://polkadot.js.org/docs/api/start/api.query.multi), I attempted to use it in several instances and was unable to get a successful response.  Do all queries support this extended syntax or is it limited to a subset of apis?

For example, I was attempting to retrieve several blocks in a single invocation, such as:
```js
api.rpc.chain.getBlock.multi(array_of_hashes, (blocks) => { ... });
```

Right now I am using `await Promise.all()` instead but was hoping using`.multi` would be slightly more performative.

I couldn't find any details in the docs regarding limitations or which functions support the use of `.multi`.

I am trying to retrieve timestamps for several finalized blocks at once and it is quite slow.  If you have any additional suggestions, it would be greatly appreciated.  Thanks!

**Comment by alfarok** [comment]
Is there a more efficient way to retrieve timestamps for multiple blocks instead of retrieving each block and decoding the extrinsics?

It looks like `api.query.timestamp.at(SOME_HASH)` was deprecated, as I was hoping to be able to do something like `api.query.timestamp.at.multi(SOME_HASHES)`.  I guess I could do a series of `apiAt.query.timestamp()` wrapped in a `promise.all()` to reduce the payload compared to getting the blocks.  Retrieving the entire payload for a series of blocks is heavy when I just need timestamps.

Also if there is a better place to ask these questions I can redirect my inquiries, but definitely appreciate you help.

**Comment by jacogr** [comment]
StackOverflow is great for these types of questions - there are always a wide variety of people that are willing to take a look and share their experiences. You can find it at https://substrate.stackexchange.com/

There is no `at.multi` since `at` executes with a specific block. Retrieving across multiple hashes are never that efficient since for each you do need the metadata (which `apiAt` and `at` retrieves internally) to construct the query. On execution, the node itself also needs to ensure it traverses the trie at that hash.

If you already have the block retrieved (if you use the optional `blockHash` query, it would already have the metadata at that point, so is is less CPU-intensive, although code-intensive) you could also look for the `timestamp.set` extrinsic in the block.
