### ISSUE TITLE
Where is the polkadot API manual?

### ISSUE THREAD

**Issue by magus777** [polkadot-js/docs#361]
This documentation does not include a proper description of all the API functionality or a list of all types of requests, parameters etc:

https://polkadot.js.org/docs/api

Is there a simple list of API requests somewhere, similar to this one for Cardano? :

https://input-output-hk.github.io/cardano-wallet/api/edge/

**Comment by jacogr** [comment]
See a sample generated from [metadata](https://polkadot.js.org/docs/api/start/basics) - https://polkadot.js.org/docs/substrate (This would obviously be very different based on the chain you connect to, since all endpoints are dynamic and decorated based on the on-chain metadata, i.e. each chain would expose different pallets)
