### ISSUE TITLE
No 'alliance' module exposed in api.query

### ISSUE THREAD

**Issue by alphainfinitus** [polkadot-js/docs#374]
Greetings, 

On the latest polkadot api (`"@polkadot/api": "^9.9.4"`) the `api.query` does not expose the 'alliance' module contrary to the [docs](https://polkadot.js.org/docs/substrate/storage#alliance).
(Using `"@polkadot/api-augment": "^9.9.4"` as well)

### Reproduction: 

On accessing it via `api.query.alliance.members('Fellow')` for example
It throws a `TypeError: Cannot read properties of undefined (reading 'members')`

With a quick console.log for `api.query` you can see that there's no alliance property in the object.

**Comment by jacogr** [comment]
It will only be on runtimes that expose it, see [the metadata decoration](https://polkadot.js.org/docs/api/start/basics#metadata).

The only 2 chains I know that have the runtime pallet is -

- Westend Collectives parachain - https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwestend-collectives-rpc.polkadot.io#/explorer
- Polkadot Collectives parachain - https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpolkadot-collectives-rpc.polkadot.io#/explorer

The docs are generated from the metadata of the Substrate kitchensink runtime (i.e. it contains anything and everything), actual runtime operation will be different due to the runtime exposing what is there. And the API making available what the runtime supports. Substrate is not static - it is runtime dynamic.

**Comment by alphainfinitus** [comment]
Hi, @jacogr thank you for the quick response.

I want to fetch the list of fellowship members.
I see that you are fetching said list in polkadot-js apps using the alliance module with the `wss://kusama.api.onfinality.io/public-ws` rpc.

I am unable to fetch using the same config.
Can you please guide me on how to achieve the same ?

**Comment by jacogr** [comment]
No, re-read above. It is not on Kusama, it is only on the Collectives parachains. One of those parachains (testing) is corrected to Westend (wss://westend-collectives-rpc.polkadot.io), another is connected to Polkadot (wss://polkadot-collectives-rpc.polkadot.io). So it is not on Westend or Polkadot itself, rather on a parachain.

On neither parachain there are alliance members as of yet. (It needs to be initialized via a system call)

**Comment by jacogr** [comment]
Sorry, I misread the second (unrelated) question. The fellowship is indeed on Kusama.

```js
// fellowshipCollective.members is a map, retrieve all entries
// https://polkadot.js.org/docs/api/start/api.query.other#map-keys--entries
const entries = await api.query.fellowshipCollective.members.entries();

// key has the accountId, (optional) value has the rank
for (let i = 0; i < entries.length; i++) {
  // key split int args part to extract
  const [{ args: [accountId] }, optRank] = entries[i];
  
  if (optRank.isSome) {
    console.log(accountId.toString(), optRank.unwrap().rank.toString());
  }
}
```

**Comment by alphainfinitus** [comment]
Oh my bad, I mistook the code in the polkadot apps. You get it via the `fellowshipCollective `module, couldn't find it in the docs.
Thanks a million for all the help.
